---
# installing nginx

- name: add repository nginx-release (CentOS6/CentOS7)
  yum: 
    name: "http://nginx.org/packages/centos/{{ansible_distribution_major_version}}/noarch/RPMS/nginx-release-centos-{{ansible_distribution_major_version}}-0.el{{ansible_distribution_major_version}}.ngx.noarch.rpm"

- name: disable the repository (pls set --enablerepo=nginx if you use it)
  replace: 
    path: /etc/yum.repos.d/nginx.repo 
    regexp: "enabled *= *1" 
    replace: "enabled=0"
  ignore_errors: True

- name: install nginx
  yum: name=nginx state=present enablerepo=nginx

- name: Start Nginx
  service: name=nginx enabled=yes state=started
